# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: cypress test from action 

on: [push]

jobs:
  cypress run:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout  
      uses: actions/checkout@v2
    - name: cypress dep`s and run test 
      uses: cypress-io/github-action@v2
 
    - run: npm run cypress:googleVisit
